Fix marker_tracker by adding missing header (#894)
Summary:
Fix build error

```
[1/7] Building CXX object CMakeFiles/marker_tracker.dir/momentum/marker_tracking/marker_tracker.cpp.o
FAILED: [code=1] CMakeFiles/marker_tracker.dir/momentum/marker_tracking/marker_tracker.cpp.o
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/bin/x86_64-conda-linux-gnu-c++ -DAXEL_WITH_TRACY_PROFILER=1 -DFMT_HEADER_ONLY=1 -DFMT_SHARED -DMOMENTUM_ENABLE_SIMD=1 -DMOMENTUM_WITH_SPDLOG=1 -DMOMENTUM_WITH_TRACY_PROFILER=1 -DSPDLOG_FMT_EXTERNAL -DSPDLOG_FWRITE_UNLOCKED -DTRACY_ENABLE -DTRACY_IMPORTS -Dmarker_tracker_EXPORTS -I/home/jeongseok/dev/momentum/issue_a -I/home/jeongseok/dev/momentum/issue_a/build/default/cpp/release -I/home/jeongseok/dev/momentum/issue_a/axel -I/home/jeongseok/dev/momentum/issue_a/build/default/cpp/release/axel -isystem /home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include -isystem /home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/tracy -isystem /home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/eigen3 -isystem /home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/dispenso/third-party/moodycamel -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include -O3 -DNDEBUG -std=gnu++20 -fPIC -march=native -pthread -fno-strict-aliasing -MD -MT CMakeFiles/marker_tracker.dir/momentum/marker_tracking/marker_tracker.cpp.o -MF CMakeFiles/marker_tracker.dir/momentum/marker_tracking/marker_tracker.cpp.o.d -o CMakeFiles/marker_tracker.dir/momentum/marker_tracking/marker_tracker.cpp.o -c /home/jeongseok/dev/momentum/issue_a/momentum/marker_tracking/marker_tracker.cpp
In file included from /home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/fmt/format.h:41,
                 from /home/jeongseok/dev/momentum/issue_a/momentum/common/exception.h:10,
                 from /home/jeongseok/dev/momentum/issue_a/momentum/character/skeleton.h:13,
                 from /home/jeongseok/dev/momentum/issue_a/momentum/character/character.h:15,
                 from /home/jeongseok/dev/momentum/issue_a/momentum/marker_tracking/marker_tracker.h:10,
                 from /home/jeongseok/dev/momentum/issue_a/momentum/marker_tracking/marker_tracker.cpp:8:
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/fmt/base.h: In instantiation of 'constexpr fmt::v11::detail::value<Context>::value(const T&, fmt::v11::detail::custom_tag) [with T = Eigen::Transpose<Eigen::Matrix<float, -1, 1> >; typename std::enable_if<(! has_formatter<T, typename Context::char_type>()), int>::type <anonymous> = 0; Context = fmt::v11::context]':
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/fmt/base.h:2235:65:   required from 'constexpr fmt::v11::detail::value<Context>::value(T&) [with T = Eigen::Transpose<Eigen::Matrix<float, -1, 1> >; typename std::enable_if<(std::integral_constant<bool, (((((((std::is_class<T>::value || std::is_enum<T>::value) || std::is_union<T>::value) || std::is_array<_Up>::value) && (! fmt::v11::detail::has_to_string_view<T, void>::value)) && (! fmt::v11::detail::is_named_arg<T>::value)) && (! fmt::v11::detail::use_format_as<T>::value)) && (! fmt::v11::detail::use_format_as_member<typename std::remove_const<T>::type, std::integral_constant<bool, true> >::value))>::value || (!1)), int>::type <anonymous> = 0; Context = fmt::v11::context]'
 2235 |   FMT_CONSTEXPR20 FMT_INLINE value(T& x) : value(x, custom_tag()) {}
      |                                                                 ^
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/fmt/base.h:2808:20:   required from 'constexpr fmt::v11::detail::format_arg_store<Context, NUM_ARGS, NUM_NAMED_ARGS, DESC> fmt::v11::make_format_args(T& ...) [with Context = context; T = {Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> >}; int NUM_ARGS = 1; int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15]'
 2808 |   return {{args...}};
      |                    ^
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/spdlog/logger.h:328:75:   required from 'void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> >}; spdlog::string_view_t = fmt::v11::basic_string_view<char>]'
  328 |             fmt::vformat_to(fmt::appender(buf), fmt, fmt::make_format_args(args...));
      |                                                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/spdlog/logger.h:80:13:   required from 'void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v11::format_string<T ...>, Args&& ...) [with Args = {Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> >}; fmt::v11::format_string<T ...> = fmt::v11::fstring<Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> > >]'
   80 |         log_(loc, lvl, details::to_string_view(fmt), std::forward<Args>(args)...);
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/spdlog/logger.h:85:12:   required from 'void spdlog::logger::log(spdlog::level::level_enum, fmt::v11::format_string<T ...>, Args&& ...) [with Args = {Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> >}; fmt::v11::format_string<T ...> = fmt::v11::fstring<Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> > >]'
   85 |         log(source_loc{}, lvl, fmt, std::forward<Args>(args)...);
      |         ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/spdlog/logger.h:140:12:   required from 'void spdlog::logger::info(fmt::v11::format_string<T ...>, Args&& ...) [with Args = {Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> >}; fmt::v11::format_string<T ...> = fmt::v11::fstring<Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> > >]'
  140 |         log(level::info, fmt, std::forward<Args>(args)...);
      |         ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/spdlog/spdlog.h:173:31:   required from 'void spdlog::info(fmt::v11::format_string<T ...>, Args&& ...) [with Args = {Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> >}; fmt::v11::format_string<T ...> = fmt::v11::fstring<Eigen::Transpose<Eigen::Matrix<float, -1, 1, 0, -1, 1> > >]'
  173 |     default_logger_raw()->info(fmt, std::forward<Args>(args)...);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeongseok/dev/momentum/issue_a/momentum/marker_tracking/marker_tracker.cpp:974:7:   required from here
   55 | #define MT_LOGI(...) ::spdlog::info(__VA_ARGS__)
      |                      ~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/jeongseok/dev/momentum/issue_a/.pixi/envs/default/include/fmt/base.h:2262:45: error: 'fmt::v11::detail::type_is_unformattable_for<Eigen::Transpose<Eigen::Matrix<float, -1, 1> >, char> _' has incomplete type
 2262 |     type_is_unformattable_for<T, char_type> _;
      |                                             ^
ninja: build stopped: subcommand failed.
```

## Checklist:

- [x] Adheres to the [style guidelines](https://facebookresearch.github.io/momentum/docs/developer_guide/style_guide)
- [x] Codebase formatted by running `pixi run lint`

Pull Request resolved: https://github.com/facebookresearch/momentum/pull/894

Test Plan:
```
pixi run test
pixi run test_py
```

Reviewed By: fbogo

Differential Revision: D89391694

Pulled By: jeongseok-meta

fbshipit-source-id: ceb1cc9666ef76617af020f8c9e96eff028df776