Fix loadFbx for a mesh with uv coordinates per vertex (#379)
Summary:
Pull Request resolved: https://github.com/facebookresearch/momentum/pull/379

I had an error in loadFbx when the UVs were per vertex instead of per polygon face:
```
RuntimeError: Mismatch between 'Direct' texture coord array size 18726 and vertex indices size 89964.
```
It appears that the fbx reading logic was missing a case.

This diff adds support for this case, and also adds a test that simply loads an fbx file with uvs per polygon face, and another one with uvs per vertex.

Reviewed By: jeongseok-meta

Differential Revision: D76430002