Fix missing cast before pybind print (#938)
Summary:
Pull Request resolved: https://github.com/facebookresearch/momentum/pull/938

Pull Request resolved: https://github.com/facebookresearch/momentum/pull/935

Fixes error with some versions of pybind11

```
======================================================================
ERROR: test_map_model_parameters (pymomentum.test.test_geometry.TestGeometry)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pymomentum/test/test_geometry.py", line 502, in test_map_model_parameters
    mp3 = pym_geometry.map_model_parameters(mp2, c, c2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to convert call argument '1' of type 'std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >' to Python object
```

Reviewed By: cstollmeta, jeongseok-meta

Differential Revision: D90632805

fbshipit-source-id: df082d2fe1f2bbcddd53f07490e44758fb40b71a