Add missing axel dependency to tensor_momentum (#727)
Summary:
Pull Request resolved: https://github.com/facebookresearch/momentum/pull/727

Fix linking error when importing geometry from pymomentum PyPI package:

```
Python 3.12.11 (main, Sep  2 2025, 14:20:58) [Clang 20.1.4 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymomentum.geometry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/jeongseok/dev/tmp/.venv/lib/python3.12/site-packages/pymomentum/geometry.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZTVN4axel3BvhIdLm4EEE
```

This was not caught by any of the CI, which is odd but could happen with different compiler settings.

Reviewed By: cdtwigg

Differential Revision: D85474531

fbshipit-source-id: f8eeb5f2c3e419c6a86973ea444cdad86c47cd94